language: cpp
compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target all --

  - cmake --build . --target clean --

  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target all --

after_script:
  - ctest
