language: cpp
compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target all --
  - cmake --build . --target package --
  - cmake --build . --target package_source --

after_script:
  - ctest
